export const TOTAL_SLIDES = 12;
export type SlideStatus =
  | 'PIPELINE: INITIALIZING'
  | 'PIPELINE: IMPERATIVO_2026'
  | 'PIPELINE: HOOK_VIDEO_LOAD'
  | 'PIPELINE: GREENOPS_BUILD'
  | 'PIPELINE: ARCH_DEPLOY'
  | 'PIPELINE: AI_STACK_LOAD'
  | 'PIPELINE: SRE_V2_CHECK'
  | 'PIPELINE: SINTESIS_TEST'
  | 'PIPELINE: HORIZONTE_2026'
  | 'PIPELINE: EMPATIA_LIVE'
  | 'PIPELINE: COMPLETE'
  | 'PIPELINE: Q&A';
export const SLIDE_STATUSES: SlideStatus[] = [
  'PIPELINE: INITIALIZING',
  'PIPELINE: IMPERATIVO_2026',
  'PIPELINE: HOOK_VIDEO_LOAD',
  'PIPELINE: GREENOPS_BUILD',
  'PIPELINE: ARCH_DEPLOY',
  'PIPELINE: AI_STACK_LOAD',
  'PIPELINE: SRE_V2_CHECK',
  'PIPELINE: SINTESIS_TEST',
  'PIPELINE: HORIZONTE_2026',
  'PIPELINE: EMPATIA_LIVE',
  'PIPELINE: COMPLETE',
  'PIPELINE: Q&A',
];
